# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15I1cR62Pm1TvZKK7b9E39If-yGJ-x6LL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
from wordcloud import WordCloud

a=pd.read_csv("/500000_Sales_Records_Cleaned.csv")

a

a.shape

a.tail()

a.head()

a.Country.unique()

a.Country.nunique()

a[a['Country']=="North Korea"]

a[a['Country']=="Morocco"]

a.shape

a.info()

a.describe()



a.drop_duplicates(['Order ID'],keep='first',inplace = True)

a.isnull()

a.isnull().sum()

a['Order ID']

a['Order ID'].unique()

a['Order ID'].nunique()

print(a['Order ID'].unique()[0])

type(a['Order ID'].unique()[0])

a['region'] = a['Region'].apply(lambda x:x[2:-2])
print(a['Region'].unique())

a['region'] = a['Region'].apply(lambda x: np.where(x == "","NA",x))
print(a['region'].unique())

a['Country'].unique()

len(a['Country'].unique())



a[a['Country'] == "Singapore"]

a['Region'].head()

a['Country'].head()

a['Country'].unique()

a['Country'].unique()

a['Country'].nunique()

a['Total Profit'].head()

a['Total Profit'].tail()

a['Total Profit'].nunique()

a['Order Priority']

a['Order Priority'].unique()

a['Order Priority'].nunique()

a['Order Priority']=a['Total Cost'].fillna("NaN")



a['Total Cost'].isnull().sum()

Country = []
a['Country'].apply(lambda x:Country.extend(x.split(",")))
Country = pd.Series(Country)
print("No.of Countries=  ", Country.nunique())

a['Country']

a['Ship Date']

a['Ship Date'].unique()

a['Ship Date'].nunique()

a['Item Type'].nunique()

a['Unit Price']

a['Units Sold'].unique()

a['Units Sold'].nunique()

a['Sales Channel']

a['Sales Channel'].unique()

len(a['Sales Channel'].unique())

a['Item Type']

a['Item Type'].unique()

a['Item Type'].nunique()

h1=[ ]
a['Item Type'].apply(lambda x:h1.extend(x.split(",")))
h1=pd.Series(h1)
print("Total unique Items =  ", h1.nunique())

a[['Item Type', 'Region', 'Sales Channel']].describe()

a['Total Revenue']

a['Unit Cost']

a['Total Cost']

